{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "206f9f8a-62b9-4791-98ba-529f648a8f23",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "import numpy as np\n",
    "\n",
    "# --- 1. Page Configuration ---\n",
    "st.set_page_config(page_title=\"Iran CO₂ Dashboard\", page_icon=\"🌍\", layout=\"wide\")\n",
    "\n",
    "# --- 2. Custom Light UI & Rounded Corners (SDG Dashboard Style) ---\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    /* Main Background */\n",
    "    .stApp {\n",
    "        background-color: #f4f7f6;\n",
    "    }\n",
    "    \n",
    "    /* Typography */\n",
    "    h1, h2, h3, h4, h5, h6, p, label, .stMarkdown {\n",
    "        color: #2c3e50 !important;\n",
    "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n",
    "    }\n",
    "    \n",
    "    /* Sidebar Styling */\n",
    "    [data-testid=\"stSidebar\"] {\n",
    "        background-color: #ffffff;\n",
    "        border-right: 1px solid #eaeded;\n",
    "        box-shadow: 2px 0 15px rgba(0,0,0,0.03);\n",
    "    }\n",
    "    \n",
    "    /* Metric Cards (KPIs) with Rounded Corners & Shadows */\n",
    "    div[data-testid=\"metric-container\"] {\n",
    "        background-color: #ffffff;\n",
    "        padding: 20px;\n",
    "        border-radius: 20px;\n",
    "        box-shadow: 0 8px 24px rgba(149, 157, 165, 0.15);\n",
    "        border: 1px solid #f0f2f6;\n",
    "        text-align: center;\n",
    "    }\n",
    "    \n",
    "    /* Metric Values */\n",
    "    [data-testid=\"stMetricValue\"] {\n",
    "        color: #2A9D8F !important; /* Stylish Teal */\n",
    "        font-weight: 800 !important;\n",
    "    }\n",
    "    \n",
    "    /* Custom CSS for Chart Containers */\n",
    "    .chart-container {\n",
    "        background-color: #ffffff;\n",
    "        padding: 20px;\n",
    "        border-radius: 20px;\n",
    "        box-shadow: 0 8px 24px rgba(149, 157, 165, 0.15);\n",
    "        margin-bottom: 25px;\n",
    "        border: 1px solid #f0f2f6;\n",
    "    }\n",
    "    </style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# --- 3. Data Loading ---\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    return pd.read_csv('Final_Clean_Data.csv')\n",
    "\n",
    "df = load_data()\n",
    "\n",
    "# --- 4. Sidebar Controls ---\n",
    "st.sidebar.markdown(\"<h1 style='text-align: center; font-size: 40px;'>🌍</h1>\", unsafe_allow_html=True)\n",
    "st.sidebar.markdown(\"<h3 style='text-align: center; color: #2A9D8F !important; font-weight: 700;'>Climate Dashboard</h3>\", unsafe_allow_html=True)\n",
    "st.sidebar.markdown(\"<p style='text-align: center; font-size: 13px; color: #7f8c8d !important;'>BS Analytics & Sustainability<br>TISS Mumbai | M2024BSASS019</p>\", unsafe_allow_html=True)\n",
    "st.sidebar.divider()\n",
    "\n",
    "st.sidebar.subheader(\"🎛️ Parameters\")\n",
    "all_countries = sorted([c for c in df['Country'].unique() if c != 'World'])\n",
    "\n",
    "target_country = st.sidebar.selectbox(\"🎯 Target Region:\", ['Iran'] + [c for c in all_countries if c != 'Iran'])\n",
    "compare_list = st.sidebar.multiselect(\"📊 Peer Comparison:\", all_countries, default=[\"India\", \"Saudi Arabia\", \"Iraq\", \"United Arab Emirates\"])\n",
    "\n",
    "min_year = int(df['Year'].min())\n",
    "max_year = int(df['Year'].max())\n",
    "selected_years = st.sidebar.slider(\"📅 Timeline:\", min_value=min_year, max_value=max_year, value=(min_year, max_year))\n",
    "\n",
    "# --- Data Slicing ---\n",
    "df_filtered = df[(df['Year'] >= selected_years[0]) & (df['Year'] <= selected_years[1])]\n",
    "df_target = df_filtered[df_filtered['Country'] == target_country]\n",
    "df_world = df_filtered[df_filtered['Country'] == 'World']\n",
    "\n",
    "latest_year_data = df_target[df_target['Year'] == df_target['Year'].max()]\n",
    "latest_data = latest_year_data.iloc[0] if not latest_year_data.empty else {'Total CO2 Emissions (Mt)': 0, 'Per Capita CO2 (Mt)': 0, 'Share of Global CO2 (%)': 0}\n",
    "\n",
    "# KPIs in Sidebar\n",
    "st.sidebar.divider()\n",
    "st.sidebar.subheader(f\"📈 Overview ({selected_years[1]})\")\n",
    "st.sidebar.metric(\"Total CO₂\", f\"{latest_data['Total CO2 Emissions (Mt)']:.1f} Mt\")\n",
    "st.sidebar.metric(\"Per Capita\", f\"{latest_data['Per Capita CO2 (Mt)']:.2f} t/person\")\n",
    "st.sidebar.metric(\"Global Share\", f\"{latest_data['Share of Global CO2 (%)']:.2f} %\")\n",
    "\n",
    "# --- 5. Main Layout ---\n",
    "st.markdown(f\"<h2 style='font-weight: 800; color: #264653 !important;'>{target_country} CO₂ Emissions Analysis</h2>\", unsafe_allow_html=True)\n",
    "st.caption(\"Investigating historical carbon footprints, economic growth, and climate responsibility.\")\n",
    "st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "\n",
    "# Plotly configuration for clean UI and downloading\n",
    "config = {\n",
    "    'displaylogo': False,\n",
    "    'modeBarButtonsToRemove': ['zoom', 'pan', 'select', 'lasso'],\n",
    "    'toImageButtonOptions': {'format': 'png', 'filename': 'TISS_Chart', 'height': 600, 'width': 1000, 'scale': 2}\n",
    "}\n",
    "\n",
    "# Clean Chart Layout Template\n",
    "layout_template = dict(\n",
    "    paper_bgcolor='rgba(0,0,0,0)',\n",
    "    plot_bgcolor='rgba(0,0,0,0)',\n",
    "    font=dict(color='#2c3e50', family=\"Segoe UI\"),\n",
    "    margin=dict(l=20, r=20, t=40, b=20),\n",
    "    xaxis=dict(showgrid=True, gridcolor='#eaeded', title_font=dict(size=14, color='#7f8c8d')),\n",
    "    yaxis=dict(showgrid=True, gridcolor='#eaeded', title_font=dict(size=14, color='#7f8c8d'))\n",
    ")\n",
    "\n",
    "# COLOR PALETTE for Charts\n",
    "C_MAIN = \"#2A9D8F\"   # Teal\n",
    "C_COMP = \"#E76F51\"   # Coral\n",
    "C_WORLD = \"#95A5A6\"  # Gray\n",
    "C_TREND = \"#E9C46A\"  # Amber\n",
    "\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "# --- Chart 1: Total CO2 Emissions ---\n",
    "with col1:\n",
    "    st.markdown('<div class=\"chart-container\">', unsafe_allow_html=True)\n",
    "    st.markdown(\"#### 📈 Total CO₂ Emissions Trend\")\n",
    "    fig1 = go.Figure()\n",
    "    fig1.add_trace(go.Scatter(x=df_target['Year'], y=df_target['Total CO2 Emissions (Mt)'], mode='lines+markers', name=target_country, line=dict(color=C_MAIN, width=3), marker=dict(size=8)))\n",
    "    \n",
    "    if len(df_target) > 1:\n",
    "        z = np.polyfit(df_target['Year'], df_target['Total CO2 Emissions (Mt)'], 1)\n",
    "        p = np.poly1d(z)\n",
    "        fig1.add_trace(go.Scatter(x=df_target['Year'], y=p(df_target['Year']), mode='lines', name='Trend', line=dict(color=C_TREND, width=2, dash='dot')))\n",
    "        \n",
    "    fig1.update_layout(**layout_template, yaxis_title=\"Total CO₂ (Mt)\")\n",
    "    st.plotly_chart(fig1, use_container_width=True, config=config)\n",
    "    st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "# --- Chart 2: Per Capita CO2 Emissions ---\n",
    "with col2:\n",
    "    st.markdown('<div class=\"chart-container\">', unsafe_allow_html=True)\n",
    "    st.markdown(\"#### 👤 Per Capita Emissions vs Global Average\")\n",
    "    fig2 = go.Figure()\n",
    "    fig2.add_trace(go.Scatter(x=df_target['Year'], y=df_target['Per Capita CO2 (Mt)'], mode='lines+markers', name=target_country, line=dict(color=C_MAIN, width=3), marker=dict(size=8)))\n",
    "    fig2.add_trace(go.Scatter(x=df_world['Year'], y=df_world['Per Capita CO2 (Mt)'], mode='lines', name='World Avg', line=dict(color=C_WORLD, width=2, dash='dash')))\n",
    "    \n",
    "    if len(df_target) > 1:\n",
    "        z = np.polyfit(df_target['Year'], df_target['Per Capita CO2 (Mt)'], 1)\n",
    "        p = np.poly1d(z)\n",
    "        fig2.add_trace(go.Scatter(x=df_target['Year'], y=p(df_target['Year']), mode='lines', name='Trend', line=dict(color=C_TREND, width=2, dash='dot')))\n",
    "\n",
    "    fig2.update_layout(**layout_template, yaxis_title=\"Per Capita CO₂ (t/person)\")\n",
    "    st.plotly_chart(fig2, use_container_width=True, config=config)\n",
    "    st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "# --- Chart 3: Peer Comparison ---\n",
    "st.markdown('<div class=\"chart-container\">', unsafe_allow_html=True)\n",
    "st.markdown(f\"#### ⚖️ Regional & Global Peer Comparison ({selected_years[1]})\")\n",
    "compare_full_list = [target_country] + compare_list\n",
    "df_latest_compare = df[(df['Year'] == selected_years[1]) & (df['Country'].isin(compare_full_list))].sort_values(by='Per Capita CO2 (Mt)', ascending=True)\n",
    "\n",
    "fig3 = px.bar(df_latest_compare, x='Per Capita CO2 (Mt)', y='Country', orientation='h', text_auto='.2f', color='Country', color_discrete_map={target_country: C_COMP})\n",
    "fig3.update_traces(marker_color=[C_COMP if c == target_country else '#264653' for c in df_latest_compare['Country']], textposition=\"outside\")\n",
    "fig3.update_layout(**layout_template, showlegend=False, xaxis_title=\"Per Capita CO₂ (t/person)\", yaxis_title=\"\")\n",
    "st.plotly_chart(fig3, use_container_width=True, config=config)\n",
    "st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "col3, col4 = st.columns(2)\n",
    "\n",
    "# --- Chart 4: GDP vs Emissions Scatter ---\n",
    "with col3:\n",
    "    st.markdown('<div class=\"chart-container\">', unsafe_allow_html=True)\n",
    "    st.markdown(\"#### 💰 Economic Growth vs Carbon Output\")\n",
    "    df_scatter = df_filtered[df_filtered['Country'].isin(compare_full_list)]\n",
    "    fig4 = px.scatter(df_scatter, x='GDP per Capita (Constant US$)', y='Total CO2 Emissions (Mt)', \n",
    "                      color='Country', hover_name='Country', size='Population', size_max=45,\n",
    "                      log_x=True, log_y=True, opacity=0.8)\n",
    "    fig4.update_layout(**layout_template)\n",
    "    st.plotly_chart(fig4, use_container_width=True, config=config)\n",
    "    st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "# --- Chart 6: Global Share Pie Chart ---\n",
    "with col4:\n",
    "    st.markdown('<div class=\"chart-container\">', unsafe_allow_html=True)\n",
    "    st.markdown(f\"#### 🌐 Global Share of Emissions ({selected_years[1]})\")\n",
    "    target_share = latest_data['Share of Global CO2 (%)'] if 'Share of Global CO2 (%)' in latest_data else 0\n",
    "    pie_data = pd.DataFrame({'Category': [target_country, 'Rest of the World'], 'Share (%)': [target_share, max(0, 100 - target_share)]})\n",
    "    fig6 = px.pie(pie_data, names='Category', values='Share (%)', hole=0.5, color='Category', color_discrete_map={target_country: C_COMP, 'Rest of the World': '#e0e6ed'})\n",
    "    fig6.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', margin=dict(l=20, r=20, t=40, b=20))\n",
    "    fig6.update_traces(textposition='inside', textinfo='percent+label')\n",
    "    st.plotly_chart(fig6, use_container_width=True, config=config)\n",
    "    st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "# --- Chart 5: Stacked Bar by Source ---\n",
    "st.markdown('<div class=\"chart-container\">', unsafe_allow_html=True)\n",
    "st.markdown(f\"#### 🏭 Sector Breakdown: Sources of Emissions ({target_country})\")\n",
    "sources = ['Coal CO2 (Mt)', 'Oil CO2 (Mt)', 'Gas CO2 (Mt)', 'Cement CO2 (Mt)', 'Flaring CO2 (Mt)']\n",
    "source_colors = ['#264653', '#E76F51', '#2A9D8F', '#F4A261', '#9b59b6']\n",
    "\n",
    "df_sources = df_target[['Year'] + sources].melt(id_vars='Year', var_name='Source', value_name='Emissions')\n",
    "fig5 = px.bar(df_sources, x='Year', y='Emissions', color='Source', color_discrete_sequence=source_colors)\n",
    "fig5.update_layout(**layout_template, barmode='stack', yaxis_title=\"CO₂ Emissions (Mt)\")\n",
    "st.plotly_chart(fig5, use_container_width=True, config=config)\n",
    "st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "# --- Download Data Option ---\n",
    "st.markdown(\"<div style='text-align: center; margin-top: 20px;'>\", unsafe_allow_html=True)\n",
    "csv = df_filtered.to_csv(index=False).encode('utf-8')\n",
    "st.download_button(label=\"📥 Download Dataset (CSV)\", data=csv, file_name='TISS_CO2_Data.csv', mime='text/csv')\n",
    "st.caption(\"Data: Our World in Data (OWID) — Global Carbon Project. Rendered for academic analysis.\")\n",
    "st.markdown(\"</div>\", unsafe_allow_html=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
